### ISSUE TITLE
运行npm run dev报错

### ISSUE THREAD

**Issue by Mike-6** [snailgis/vue_webgis#53]
PS D:\Test\test\vue_webgis-master> npm run dev

> vue-webgis@1.0.0 dev
> concurrently "npm run server" "npm run client"

[0]
[0] > vue-webgis@1.0.0 server
[0] > nodemon server.js
[0]
[1]
[1] > vue-webgis@1.0.0 client
[1] > npm start --prefix client
[1]
[0] [nodemon] 2.0.20
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching path(s): *.*
[0] [nodemon] watching extensions: js,mjs,json
[0] [nodemon] starting `node server.js`
[0] node:internal/modules/cjs/loader:936
[0]   throw err;
[0]   ^
[0]
[0] Error: Cannot find module 'D:\Test\test\vue_webgis-master\node_modules\bcrypt\lib\binding\napi-v3\bcrypt_lib.node'
[0] Require stack:
[0] - D:\Test\test\vue_webgis-master\node_modules\bcrypt\bcrypt.js
[0] - D:\Test\test\vue_webgis-master\routers\api\users.js
[0] - D:\Test\test\vue_webgis-master\server.js
[0]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[0]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[0]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[0]     at require (node:internal/modules/cjs/helpers:102:18)
[0]     at Object.<anonymous> (D:\Test\test\vue_webgis-master\node_modules\bcrypt\bcrypt.js:6:16)
[0]     at Module._compile (node:internal/modules/cjs/loader:1101:14)
[0]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
[0]     at Module.load (node:internal/modules/cjs/loader:981:32)
[0]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[0]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[0]     at require (node:internal/modules/cjs/helpers:102:18)
[0]     at Object.<anonymous> (D:\Test\test\vue_webgis-master\routers\api\users.js:3:16)
[0]     at Module._compile (node:internal/modules/cjs/loader:1101:14)
[0]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
[0]     at Module.load (node:internal/modules/cjs/loader:981:32)
[0]     at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
[0]   code: 'MODULE_NOT_FOUND',
[0]   requireStack: [
[0]     'D:\\Test\\test\\vue_webgis-master\\node_modules\\bcrypt\\bcrypt.js',
[0]     'D:\\Test\\test\\vue_webgis-master\\routers\\api\\users.js',
[0]     'D:\\Test\\test\\vue_webgis-master\\server.js'
[0]   ]
[0] }
[0] [nodemon] app crashed - waiting for file changes before starting...
[1]
[1] > client@0.1.0 start
[1] > npm run serve
[1]
[1]
[1] > client@0.1.0 serve
[1] > vue-cli-service serve
[1]
[1] 'vue-cli-service' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
[1] ���������ļ���
[1] npm run client exited with code 1

**Comment by Lesliewxj** [comment]
我也遇到了同样的问题

**Comment by fw02247** [comment]
没安装nodemon包。
在主文件夹`npm install nodemon`
`npm install bcrypt`
